global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'tcp_probe'
    metrics_path: /probe
    params:
      module: [tcp_tls_verification]
    static_configs:
      - targets:
          - 'example.com:443'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'smtp_probe'
    metrics_path: /probe
    params:
      module: [smtp_tls_handshake]
    static_configs:
      - targets:
        - 'example.com:25'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
